publisher_forward_position_controller:
  ros__parameters:

    wait_sec_between_publish: 2
    publish_topic: "/forward_position_controller/commands"

    goal_names: ["pos0", "pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7", "pos8"]
    pos0: [0.125, 0.263]
    pos1: [0.385, 0.385]
    pos2: [0.785, 0.785]
    pos3: [0.385, 0.385]
    pos4: [0, 0]
    pos5: [-0.385, -0.385]
    pos6: [-0.785, -0.785]
    pos7: [-0.385, -0.385]
    pos8: [0, 0]
